name: Continuous Integration

on:
  pull_request: 
    branches:
      - main
      - master
        
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout code from Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Install dependencies
      - name: Install dependencies
        run: go mod download