name: Continuous Integration

on:
  pull_request: 
    branches:
      - main
      - master
        
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout code from Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          
      # Display Go version
      - name: Display Go version
        run: go version

      # Verify dependencies
      - name: Verify dependencies
        run: go mod verify
      
      # Build
      - name: Build
        run: go build -v ./cmd/app
        
      # Test
      - name: Test
        run: go test -v ./...